const text = [
  `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
  `Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.`,
  `Ut id urna at risus pretium viverra ullamcorper in ipsum. Proin vel elit lorem. Phasellus non elit quis mauris laoreet laoreet. Proin ullamcorper, felis id commodo molestie, lacus ligula semper enim, sed rutrum sapien elit vel erat. Integer ligula eros, efficitur ac aliquet non, laoreet a lacus. Nam varius pulvinar lacus, ac iaculis mi rutrum finibus. Suspendisse mollis ligula quis ante ultrices bibendum. Curabitur felis velit, euismod in fringilla at, elementum in dolor.`,
  `It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).`,
  `There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.`,
  `Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur id lectus ut eros pretium mollis quis id nulla. Phasellus suscipit et ligula quis tincidunt. Vestibulum a euismod quam. Suspendisse potenti. Mauris posuere nunc non leo pretium, ut ornare mauris aliquet. Duis quis molestie metus. Nullam mattis, sem sit amet pellentesque venenatis, velit urna pellentesque nisi, a mollis mi nisl eu turpis. Vivamus sit amet odio augue. Etiam viverra scelerisque dolor vitae euismod. Sed id purus dictum, auctor nulla ac, convallis dui. Mauris nec lacus est. Fusce ipsum quam, aliquet in bibendum quis, lacinia at felis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam blandit felis a erat convallis, vel pulvinar velit volutpat. Cras at mollis ex.`,
  `Integer imperdiet, leo at facilisis fermentum, elit nunc rutrum ipsum, id interdum nibh urna vitae lacus. Quisque venenatis ligula vitae augue lacinia, id tincidunt enim tempus. Vestibulum id massa in tellus congue luctus ac non tellus. Aliquam ac scelerisque massa, et tincidunt sem. Nullam ornare ultrices odio vitae interdum. Nullam sagittis elit eu dui sollicitudin venenatis. Praesent eget est ac odio malesuada venenatis quis a augue. Phasellus tempor tincidunt augue, a imperdiet nulla mollis vitae.`,
  `Vestibulum euismod vestibulum lacinia. Integer ornare iaculis dignissim. Vestibulum et lorem leo. Cras elementum arcu eget dolor dignissim lobortis. Morbi elementum lorem massa, a elementum nisi imperdiet vitae. Vivamus sit amet pellentesque diam, convallis bibendum leo. Nunc nec pulvinar dolor. Curabitur varius feugiat accumsan. Nulla facilisis non eros sit amet sodales. Aenean convallis, elit at convallis posuere, orci quam accumsan eros, ac vestibulum sem quam ut quam. Nulla euismod neque a augue iaculis ornare. Mauris rutrum velit eleifend, dictum lorem eu, blandit turpis.`,
  `Vestibulum et purus nunc. Mauris ornare libero vel nibh efficitur dictum. Proin eros sapien, ultrices id metus nec, tincidunt aliquet enim. Nullam blandit sapien in eros accumsan, et pharetra urna ullamcorper. Fusce sed ultricies est. Nunc felis neque, imperdiet eu ante vel, elementum ultrices mi. Donec leo enim, semper consectetur ullamcorper vel, imperdiet eget nunc. Aenean ultrices risus et risus gravida, id vestibulum risus faucibus. Ut at ligula mollis, accumsan felis interdum, hendrerit ligula.`,
  `Curabitur fermentum ipsum non dui rutrum ultrices. Nullam est nisi, tincidunt nec sem id, efficitur ornare mi. Maecenas sed sagittis sem, sed auctor purus. Donec pharetra imperdiet eros nec volutpat. In ipsum erat, pellentesque id dignissim nec, mollis vel ex. Praesent at ullamcorper neque. Morbi vitae congue ex.`,
  `Duis id congue massa. Maecenas pulvinar, tellus ac pretium tincidunt, mi ipsum ultricies dui, ut tristique ante augue vitae elit. Fusce pellentesque varius risus et fringilla. Morbi odio ex, vulputate eu consectetur sed, rutrum ut sapien. Cras fermentum ex leo, vitae rhoncus lacus dignissim nec. Maecenas laoreet consequat magna, at iaculis orci finibus ac. Curabitur aliquam auctor pulvinar. Vestibulum porttitor molestie vulputate. Donec ultricies at lorem et efficitur. Mauris at lobortis turpis. Etiam nec mattis ligula.`,
];
export default text;
